#!/usr/bin/env python3
"""
Generate a CloudFormation template for the deception detection pipeline
based on selected scenarios.

Usage:
    python generate-detection-stack.py --scenarios 1,2,3,8
    python generate-detection-stack.py --scenarios 1,2,3,4,5,6,7,8 --email alerts@company.com
    python generate-detection-stack.py --all
    python generate-detection-stack.py --scenarios 2 --output my-stack.yaml

The script reads event rule templates from event-rules/scenario-XX.json
and generates a complete CFT with:
  - SNS Topic + email subscription
  - Detection Lambda (with scenario registry filtered to selected scenarios)
  - Per-scenario EventBridge rules (ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS)
  - All required IAM permissions
"""

import argparse
import json
import os
import sys
import yaml


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
EVENT_RULES_DIR = os.path.join(PROJECT_ROOT, "event-rules")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "test-infra")

ALL_SCENARIOS = list(range(1, 20))  # 1-19

DEFAULT_EMAIL = "devanshunagpal@fico.com"


def load_event_rule(scenario_num):
    """Load an event rule JSON file for a scenario."""
    filename = f"scenario-{scenario_num:02d}.json"
    filepath = os.path.join(EVENT_RULES_DIR, filename)
    if not os.path.exists(filepath):
        print(f"WARNING: No event rule file found for scenario {scenario_num} at {filepath}")
        return None
    with open(filepath, "r") as f:
        return json.load(f)


def sanitize_name(name):
    """Convert a scenario name to a CloudFormation-safe logical ID."""
    return name.replace("-", "").replace("_", "").title().replace(" ", "")


def generate_template(scenarios, email):
    """Generate the full CloudFormation template."""

    # Load all selected event rules
    rules = {}
    for s in scenarios:
        rule = load_event_rule(s)
        if rule:
            rules[s] = rule

    if not rules:
        print("ERROR: No valid event rules found for selected scenarios.")
        sys.exit(1)

    print(f"Generating detection stack for scenarios: {sorted(rules.keys())}")
    print(f"Alert email: {email}")

    # Build the template
    template = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": f"Deception Detection Pipeline — Scenarios {','.join(str(s) for s in sorted(rules.keys()))}. "
                       f"Auto-generated by generate-detection-stack.py",
        "Parameters": {
            "AlertEmail": {
                "Type": "String",
                "Default": email,
                "Description": "Email address to receive deception alerts"
            }
        },
        "Resources": {},
        "Outputs": {}
    }

    resources = template["Resources"]
    outputs = template["Outputs"]

    # ─── SNS Topic ───────────────────────────────────────────────────
    resources["DeceptionAlertTopic"] = {
        "Type": "AWS::SNS::Topic",
        "Properties": {
            "TopicName": "deception-alerts",
            "DisplayName": "Deception Alert"
        }
    }

    resources["DeceptionAlertEmailSubscription"] = {
        "Type": "AWS::SNS::Subscription",
        "Properties": {
            "TopicArn": {"Ref": "DeceptionAlertTopic"},
            "Protocol": "email",
            "Endpoint": {"Ref": "AlertEmail"}
        }
    }

    resources["DeceptionAlertTopicPolicy"] = {
        "Type": "AWS::SNS::TopicPolicy",
        "Properties": {
            "Topics": [{"Ref": "DeceptionAlertTopic"}],
            "PolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [{
                    "Sid": "AllowLambdaPublish",
                    "Effect": "Allow",
                    "Principal": {"Service": "lambda.amazonaws.com"},
                    "Action": "sns:Publish",
                    "Resource": {"Ref": "DeceptionAlertTopic"}
                }]
            }
        }
    }

    # ─── Lambda IAM Role ─────────────────────────────────────────────
    resources["DetectionLambdaRole"] = {
        "Type": "AWS::IAM::Role",
        "Properties": {
            "RoleName": "deception-detection-lambda-role",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [{
                    "Effect": "Allow",
                    "Principal": {"Service": "lambda.amazonaws.com"},
                    "Action": "sts:AssumeRole"
                }]
            },
            "Policies": [{
                "PolicyName": "deception-detection-policy",
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "CloudWatchLogs",
                            "Effect": "Allow",
                            "Action": [
                                "logs:CreateLogGroup",
                                "logs:CreateLogStream",
                                "logs:PutLogEvents"
                            ],
                            "Resource": {"Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/deception-detection-handler:*"}
                        },
                        {
                            "Sid": "SNSPublish",
                            "Effect": "Allow",
                            "Action": ["sns:Publish"],
                            "Resource": {"Ref": "DeceptionAlertTopic"}
                        }
                    ]
                }
            }]
        }
    }

    # ─── Lambda Function ─────────────────────────────────────────────
    # Build filtered scenario registry for the Lambda code
    registry_lines = []
    for s in sorted(rules.keys()):
        r = rules[s]
        registry_lines.append(f'    {s}: {{"description": "{r["scenario_name"]}", "events": {json.dumps(r["event_pattern"]["detail"]["eventName"])}}}')

    registry_str = "{\n" + ",\n".join(registry_lines) + "\n}"

    lambda_code = '''import json
import os
import logging
import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

sns = boto3.client('sns')
SNS_TOPIC_ARN = os.environ['SNS_TOPIC_ARN']

CRITICAL_EVENTS = {
    "GetSecretValue", "GetObject", "Scan", "Query", "GetItem",
    "ReceiveMessage", "GetLogEvents", "BatchGetImage", "Decrypt",
    "GetFunctionConfiguration20150331v2", "DescribeStacks", "DescribeKey",
    "GetSAMLProvider", "GetTopicAttributes", "GetQueueAttributes",
    "ListSubscriptionsByTopic", "FilterLogEvents", "GetDownloadUrlForLayer",
    "StartInstances", "AuthorizeSecurityGroupIngress", "Publish",
    "GetParameter", "GetParametersByPath", "DescribeTable"
}

def handler(event, context):
    try:
        detail = event.get("detail")
        if not detail:
            logger.error(f"No detail field: {json.dumps(event)[:500]}")
            return {"statusCode": 400}

        event_name = detail.get("eventName", "unknown")
        account_id = detail.get("recipientAccountId", detail.get("userIdentity", {}).get("accountId", "unknown"))
        event_time = detail.get("eventTime", "unknown")
        source_ip = detail.get("sourceIPAddress", "unknown")
        user_arn = detail.get("userIdentity", {}).get("arn", "unknown")
        region = detail.get("awsRegion", "unknown")

        # Extract resource
        params = detail.get("requestParameters") or {}
        resource_name = (params.get("roleName") or params.get("functionName") or
                        params.get("tableName") or params.get("secretId") or
                        params.get("name") or params.get("keyId") or
                        params.get("logGroupName") or params.get("repositoryName") or
                        params.get("stackName") or params.get("queueUrl", "").rsplit("/", 1)[-1] or
                        "unknown")

        severity = "CRITICAL" if event_name in CRITICAL_EVENTS else "HIGH"

        # Determine which rule matched (from the rule name in the event)
        rule_name = event.get("resources", [""])[0].split("/")[-1] if event.get("resources") else "unknown-rule"

        emoji = "\\U0001f6a8" if severity == "CRITICAL" else "\\u26a0\\ufe0f"
        email_body = (
            f"{emoji} DECEPTION ALERT - {severity}\\n"
            f"{'=' * 50}\\n\\n"
            f"Rule:        {rule_name}\\n"
            f"Account:     {account_id}\\n"
            f"Event:       {event_name}\\n"
            f"Time (UTC):  {event_time}\\n"
            f"Source IP:   {source_ip}\\n"
            f"User:        {user_arn}\\n"
            f"Resource:    {resource_name}\\n"
            f"Region:      {region}\\n"
        )

        sns.publish(
            TopicArn=SNS_TOPIC_ARN,
            Subject=f"[{severity}] Deception Alert - {event_name} on {resource_name}",
            Message=email_body
        )

        logger.info(f"ALERT: {severity} | {event_name} | {resource_name} | {account_id}")
        return {"statusCode": 200}

    except Exception as e:
        logger.error(f"Error: {str(e)}", exc_info=True)
        raise
'''

    resources["DetectionLambdaFunction"] = {
        "Type": "AWS::Lambda::Function",
        "Properties": {
            "FunctionName": "deception-detection-handler",
            "Description": f"Detection Lambda for scenarios {','.join(str(s) for s in sorted(rules.keys()))}",
            "Runtime": "python3.12",
            "Handler": "index.handler",
            "Timeout": 30,
            "MemorySize": 256,
            "ReservedConcurrentExecutions": 10,
            "Role": {"Fn::GetAtt": ["DetectionLambdaRole", "Arn"]},
            "Environment": {
                "Variables": {
                    "SNS_TOPIC_ARN": {"Ref": "DeceptionAlertTopic"}
                }
            },
            "Code": {
                "ZipFile": lambda_code
            }
        }
    }

    resources["DetectionLambdaLogGroup"] = {
        "Type": "AWS::Logs::LogGroup",
        "Properties": {
            "LogGroupName": "/aws/lambda/deception-detection-handler",
            "RetentionInDays": 30
        }
    }

    # ─── Per-Scenario EventBridge Rules ──────────────────────────────
    for s in sorted(rules.keys()):
        rule = rules[s]
        logical_id = f"DeceptionRule{s:02d}"
        permission_id = f"LambdaPermission{s:02d}"

        resources[logical_id] = {
            "Type": "AWS::Events::Rule",
            "Properties": {
                "Name": rule["name"],
                "Description": rule["description"],
                "State": "ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS",
                "EventPattern": rule["event_pattern"],
                "Targets": [{
                    "Id": f"DetectionLambdaScenario{s:02d}",
                    "Arn": {"Fn::GetAtt": ["DetectionLambdaFunction", "Arn"]}
                }]
            }
        }

        resources[permission_id] = {
            "Type": "AWS::Lambda::Permission",
            "Properties": {
                "FunctionName": {"Ref": "DetectionLambdaFunction"},
                "Action": "lambda:InvokeFunction",
                "Principal": "events.amazonaws.com",
                "SourceArn": {"Fn::GetAtt": [logical_id, "Arn"]}
            }
        }

    # ─── Outputs ─────────────────────────────────────────────────────
    outputs["DetectionLambdaArn"] = {
        "Description": "ARN of the Detection Lambda",
        "Value": {"Fn::GetAtt": ["DetectionLambdaFunction", "Arn"]}
    }
    outputs["SNSTopicArn"] = {
        "Description": "ARN of the alert SNS topic",
        "Value": {"Ref": "DeceptionAlertTopic"}
    }
    outputs["AlertEmail"] = {
        "Description": "Email receiving alerts (confirm subscription in inbox)",
        "Value": {"Ref": "AlertEmail"}
    }
    outputs["ScenariosDeployed"] = {
        "Description": "Scenario numbers with active detection rules",
        "Value": ",".join(str(s) for s in sorted(rules.keys()))
    }

    return template


def main():
    parser = argparse.ArgumentParser(
        description="Generate a CloudFormation detection stack for selected deception scenarios"
    )
    parser.add_argument(
        "--scenarios", "-s",
        type=str,
        help="Comma-separated scenario numbers (e.g., 1,2,3,8)"
    )
    parser.add_argument(
        "--all", "-a",
        action="store_true",
        help="Include all 19 scenarios"
    )
    parser.add_argument(
        "--email", "-e",
        type=str,
        default=DEFAULT_EMAIL,
        help=f"Alert email address (default: {DEFAULT_EMAIL})"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default=None,
        help="Output file path (default: test-infra/02-detection-pipeline-generated.yaml)"
    )

    args = parser.parse_args()

    # Determine scenarios
    if args.all:
        scenarios = ALL_SCENARIOS
    elif args.scenarios:
        try:
            scenarios = [int(s.strip()) for s in args.scenarios.split(",")]
        except ValueError:
            print("ERROR: --scenarios must be comma-separated numbers (e.g., 1,2,3,8)")
            sys.exit(1)
    else:
        print("ERROR: Specify --scenarios or --all")
        parser.print_help()
        sys.exit(1)

    # Validate scenario numbers
    for s in scenarios:
        if s < 1 or s > 19:
            print(f"ERROR: Invalid scenario number {s}. Valid range: 1-19")
            sys.exit(1)

    # Generate template
    template = generate_template(scenarios, args.email)

    # Write output
    output_path = args.output or os.path.join(OUTPUT_DIR, "02-detection-pipeline-generated.yaml")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w") as f:
        yaml.dump(template, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"\n✅ Generated: {output_path}")
    print(f"   Scenarios: {sorted(scenarios)}")
    print(f"   Rules: {len([s for s in scenarios if load_event_rule(s)])}")
    print(f"   Email: {args.email}")
    print(f"\n   Deploy with:")
    print(f"   aws cloudformation deploy --template-file {output_path} --stack-name deception-detection --capabilities CAPABILITY_NAMED_IAM")


if __name__ == "__main__":
    main()
