package naming

import (
	"fmt"
	"os"
	"strings"
)

// GenerateTFVars generates a resolved.tfvars file content from resolved names.
// requiredVars is the list of Terraform variable names from the scenario manifest.
// resolved is the map of tf_variable → resolvedName.
// accountID and region are added unconditionally (all scenarios need them).
func GenerateTFVars(
	requiredVars []string,
	resolved map[string]string,
	accountID, region string,
	extra map[string]string,
) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Generated by mirage — do not edit manually.\n")
	sb.WriteString("# This file is regenerated on every deploy.\n\n")

	// Always include account_id and region if required.
	allVars := map[string]string{
		"account_id": accountID,
		"region":     region,
	}

	for k, v := range resolved {
		allVars[k] = v
	}
	for k, v := range extra {
		allVars[k] = v
	}

	for _, varName := range requiredVars {
		val, ok := allVars[varName]
		if !ok {
			return "", fmt.Errorf("no resolved value for required Terraform variable %q", varName)
		}
		sb.WriteString(fmt.Sprintf("%s = %q\n", varName, val))
	}

	return sb.String(), nil
}

// WriteTFVars writes the tfvars content to a file at the given path.
// The file is written with 0600 permissions (operator-only read/write).
func WriteTFVars(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("write tfvars %s: %w", path, err)
	}
	return nil
}

// ScenarioKey returns the string key used for naming overrides lookup.
// Convention: "scenario-N" where N is the scenario number.
func ScenarioKey(number int) string {
	return fmt.Sprintf("scenario-%d", number)
}
