package tf

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	// StateDir is the root directory for all Terraform state files under ~/.mirage/.
	StateDir = "tf-state"
)

// StatePath returns the isolated state directory for a given scope.
// Convention: ~/.mirage/tf-state/<component>/<spoke-alias|hub>/<module>/
// Examples:
//   - ~/.mirage/tf-state/scenarios/spoke-dev/scenario-7/
//   - ~/.mirage/tf-state/roles/spoke-dev/
//   - ~/.mirage/tf-state/monitoring/hub/brain/
func StatePath(mirageDir, component, scope, module string) string {
	return filepath.Join(mirageDir, StateDir, component, scope, module)
}

// EnsureStateDir creates the state directory if it does not exist.
func EnsureStateDir(statePath string) error {
	if err := os.MkdirAll(statePath, 0700); err != nil {
		return fmt.Errorf("create state dir %s: %w", statePath, err)
	}
	return nil
}

// WorkDir returns the working directory for a Terraform operation.
// For roles: templates/roles/<module>
// For scenarios: aws/scenarios_terraform/scenario-N  (source templates)
// The workdir contains the .tf files; state is stored separately in StatePath.
func WorkDir(repoRoot, component, module string) string {
	switch component {
	case "roles":
		return filepath.Join(repoRoot, "Mirage-cli", "templates", "roles", module)
	case "monitoring":
		return filepath.Join(repoRoot, "Mirage-cli", "templates", "monitoring", module)
	case "scenarios":
		return filepath.Join(repoRoot, "aws", "scenarios_terraform", module)
	default:
		return filepath.Join(repoRoot, "Mirage-cli", "templates", component, module)
	}
}

// BackendConfig generates a local Terraform backend config that stores state
// in the isolated StatePath instead of the template directory.
// This prevents state file collisions when the same template is deployed
// for multiple spokes or scenarios.
func BackendConfig(statePath string) string {
	return fmt.Sprintf(`
terraform {
  backend "local" {
    path = "%s/terraform.tfstate"
  }
}
`, statePath)
}

// WriteBackendOverride writes a backend_override.tf to workDir that redirects
// state to the isolated StatePath. This is the Terraform-approved method for
// overriding backend config without modifying source .tf files.
func WriteBackendOverride(workDir, statePath string) error {
	content := fmt.Sprintf(`# Generated by mirage — redirects state to isolated path.
# Do not commit this file.
terraform {
  backend "local" {
    path = %q
  }
}
`, filepath.Join(statePath, "terraform.tfstate"))

	overridePath := filepath.Join(workDir, "backend_override.tf")
	if err := os.WriteFile(overridePath, []byte(content), 0600); err != nil {
		return fmt.Errorf("write backend override: %w", err)
	}
	return nil
}

// RemoveBackendOverride cleans up the override file after the operation.
func RemoveBackendOverride(workDir string) {
	_ = os.Remove(filepath.Join(workDir, "backend_override.tf"))
}

// StateExists reports whether a Terraform state file exists for the given path.
func StateExists(statePath string) bool {
	tfstate := filepath.Join(statePath, "terraform.tfstate")
	info, err := os.Stat(tfstate)
	if err != nil {
		return false
	}
	return info.Size() > 10 // non-empty state file
}

// ListDeployedScenarios scans the state dir and returns deployed scenario numbers.
func ListDeployedScenarios(mirageDir, spokeAlias string) []int {
	scenarioStateDir := filepath.Join(mirageDir, StateDir, "scenarios", spokeAlias)
	entries, err := os.ReadDir(scenarioStateDir)
	if err != nil {
		return nil
	}
	var deployed []int
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		var n int
		if _, err := fmt.Sscanf(e.Name(), "scenario-%d", &n); err == nil {
			statePath := filepath.Join(scenarioStateDir, e.Name())
			if StateExists(statePath) {
				deployed = append(deployed, n)
			}
		}
	}
	return deployed
}
