package tf

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// VarFile represents a generated .tfvars file with its content and hash.
type VarFile struct {
	Path    string
	Content string
	Hash    string // SHA256 of content
}

// BuildVarFile generates a .tfvars file in the given directory from a map.
// Keys that are empty strings are omitted (optional variables).
func BuildVarFile(dir string, vars map[string]string) (*VarFile, error) {
	var sb strings.Builder
	sb.WriteString("# Generated by mirage — do not commit or edit manually.\n")
	sb.WriteString("# Recreated on every deploy from ~/.mirage/config.yaml\n\n")

	for k, v := range vars {
		if v == "" {
			continue // skip unset optional variables
		}
		sb.WriteString(fmt.Sprintf("%s = %q\n", k, v))
	}

	content := sb.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))

	path := filepath.Join(dir, "mirage-resolved.tfvars")
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return nil, fmt.Errorf("write var file %s: %w", path, err)
	}

	return &VarFile{
		Path:    path,
		Content: content,
		Hash:    hash,
	}, nil
}

// Remove deletes the var file (used in defer to clean up before destroy).
func (v *VarFile) Remove() {
	_ = os.Remove(v.Path)
}

// RequiredVarsPresent checks that all required variable names have non-empty values.
func RequiredVarsPresent(required []string, vars map[string]string) error {
	var missing []string
	for _, r := range required {
		if vars[r] == "" {
			missing = append(missing, r)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required Terraform variables: %v\n"+
			"These are resolved from ~/.mirage/config.yaml — run `mirage config show` to inspect", missing)
	}
	return nil
}

// MirageVarsForScenario builds the standard variable map for a scenario deploy.
// resolver resolves resource names; requiredVarNames comes from scenario.yaml.
func MirageVarsForScenario(
	accountID, region, spokeAlias string,
	resolvedNames map[string]string,
) map[string]string {
	vars := map[string]string{
		"account_id":  accountID,
		"region":      region,
		"spoke_alias": spokeAlias,
	}
	// Merge resolved resource names (type → name).
	for k, v := range resolvedNames {
		vars[k] = v
	}
	return vars
}
