variable "account_id" {
  type        = string
  description = "AWS Account ID for trust and resource policies"
}

variable "saml_metadata_document" {
  type        = string
  description = "SAML metadata XML document (generated by deploy.sh)"
}
