apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://A1B2C3D4E5.gr7.us-west-2.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZDN3YzNMQXhFVEF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBek1UVXhNREF3TURCYUZ3MHpOREF6TVRNeE1EQXdNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM2cjhVT0
    name: arn:aws:eks:us-west-2:123456789012:cluster/prod-platform-cluster
contexts:
  - context:
      cluster: arn:aws:eks:us-west-2:123456789012:cluster/prod-platform-cluster
      user: cluster-admin
      namespace: default
    name: prod-platform-admin
current-context: prod-platform-admin
users:
  - name: cluster-admin
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6InRFVGR4ajZOVU1CZ3dCTjFobjRSRnlKNjRfSm9OdWFMWHFqYzVKZDFuWXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjbHVzdGVyLWFkbWluLXRva2VuLXg5OHc3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmNsdXN0ZXItYWRtaW4ifQ.Tz3qK7mV9xR2pN4wL8yH5jF6gB0cA1dE2iO3uS4tY7vW8xZ9aQ0bC1dE2fG3hI4jK5lM6nO7pQ8rS9tU0vW
